In [14]:
import pandas as pd

samples = pd.read_excel(r'/Users/greysonnewton/Library/CloudStorage/OneDrive-UniversityOfHouston/FALL_2025/Big Data Analytics (PETR)/big-data-analytics/big-data-analytics/homeworks/hw4/k_phi.xlsx')

sample_pressures = pd.read_excel(r'/Users/greysonnewton/Library/CloudStorage/OneDrive-UniversityOfHouston/FALL_2025/Big Data Analytics (PETR)/big-data-analytics/big-data-analytics/homeworks/hw4/pc_hw4.xlsx')
sample_pressures = sample_pressures.drop('pc(psi)', axis=1)
sample_pressures = sample_pressures.T
sample_pressures.index = sample_pressures.index.astype(int)+1
sample_pressures.index.name = 'Sample'
sample_pressures.tail()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
Sample,,,,,,,,,,,,,,,,,,,,,
103,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,46.7,41.6,38.4,35.7,33.0,30.3,27.6,25.2,23.1,21.0
104,100.0,100.0,100.0,99.7,99.4,99.3,99.1,99.1,98.8,98.8,...,37.1,33.1,30.0,27.5,25.3,22.9,20.6,18.3,16.6,14.7
105,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,98.9,97.9,96.9,95.7,77.7,55.1,45.1,36.9,29.8,29.8
106,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,61.2,54.8,47.8,41.0,34.8,29.4,24.8,21.1,18.0,15.0
107,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,76.7,67.2,60.7,54.9,48.7,42.4,37.5,33.3,29.7,26.0

# Data Preprocessing

In [2]:
samples = samples.drop('depth (ft)', axis=1)\
    .set_index('Sample')
print(samples.shape)
samples

(106, 2)

        permeability (md)  porosity (%)
Sample
1                29.00000          21.7
2                11.50000          19.9
3                 7.96000          19.2
4                24.00000          22.1
5                 2.07000          19.8
...                   ...           ...
102               0.00275          10.9
103               0.00750          12.7
104               0.00208           6.4
105               0.00247           9.7
106               0.00062           5.5

[106 rows x 2 columns]

In [86]:
sample_pressures = sample_pressures.rename(
    columns={
        col: f"r_{col}"
        for col in sample_pressures.columns
        if any(char.isdigit() for char in str(col))  # Ensure col is converted to string
    }
)
print(sample_pressures.shape)
sample_pressures.T

(36, 107)

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
pc(psi),0.0,0.0,2.0,2.5,3.3,4.3,5.5,7.2,9.3,12.0,...,925.0,1200.0,1550.0,2000.0,2600.0,3350.0,4300.0,5550.0,7200.0,9300.0
r_1,100.0,100.0,100.0,99.8,99.7,99.6,99.4,99.3,99.0,98.8,...,16.7,15.3,13.8,12.0,10.5,9.3,8.0,7.1,6.2,5.4
r_2,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.9,...,23.0,20.6,18.3,16.3,14.3,12.5,11.0,9.6,8.6,7.6
r_3,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,20.7,18.7,16.1,14.3,12.2,10.3,8.7,7.4,6.2,5.2
r_4,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.9,99.7,99.6,...,15.3,12.8,11.2,9.6,8.3,6.9,5.8,5.1,4.2,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
r_102,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,46.7,41.6,38.4,35.7,33.0,30.3,27.6,25.2,23.1,21.0
r_103,100.0,100.0,100.0,99.7,99.4,99.3,99.1,99.1,98.8,98.8,...,37.1,33.1,30.0,27.5,25.3,22.9,20.6,18.3,16.6,14.7
r_104,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,98.9,97.9,96.9,95.7,77.7,55.1,45.1,36.9,29.8,29.8
r_105,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,61.2,54.8,47.8,41.0,34.8,29.4,24.8,21.1,18.0,15.0
r_106,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,76.7,67.2,60.7,54.9,48.7,42.4,37.5,33.3,29.7,26.0

In [87]:
sample_pressures = sample_pressures.T.reset_index()
sample_pressures = sample_pressures.drop('index', axis=1)
sample_pressures.index.name = 'Sample'
print(sample_pressures.shape)
sample_pressures

(107, 36)

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
Sample,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,2.0,2.5,3.3,4.3,5.5,7.2,9.3,12.0,...,925.0,1200.0,1550.0,2000.0,2600.0,3350.0,4300.0,5550.0,7200.0,9300.0
1,100.0,100.0,100.0,99.8,99.7,99.6,99.4,99.3,99.0,98.8,...,16.7,15.3,13.8,12.0,10.5,9.3,8.0,7.1,6.2,5.4
2,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.9,...,23.0,20.6,18.3,16.3,14.3,12.5,11.0,9.6,8.6,7.6
3,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,20.7,18.7,16.1,14.3,12.2,10.3,8.7,7.4,6.2,5.2
4,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.9,99.7,99.6,...,15.3,12.8,11.2,9.6,8.3,6.9,5.8,5.1,4.2,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,46.7,41.6,38.4,35.7,33.0,30.3,27.6,25.2,23.1,21.0
103,100.0,100.0,100.0,99.7,99.4,99.3,99.1,99.1,98.8,98.8,...,37.1,33.1,30.0,27.5,25.3,22.9,20.6,18.3,16.6,14.7
104,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,98.9,97.9,96.9,95.7,77.7,55.1,45.1,36.9,29.8,29.8
105,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,61.2,54.8,47.8,41.0,34.8,29.4,24.8,21.1,18.0,15.0
106,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,76.7,67.2,60.7,54.9,48.7,42.4,37.5,33.3,29.7,26.0

In [88]:
df = samples.join(sample_pressures).sort_index(ascending=True)
print(df.shape)
df

(106, 38)

,permeability (md),porosity (%),0,1,2,3,4,5,6,7,...,26,27,28,29,30,31,32,33,34,35
Sample,,,,,,,,,,,,,,,,,,,,,
1,29.00000,21.7,100.0,100.0,100.0,99.8,99.7,99.6,99.4,99.3,...,16.7,15.3,13.8,12.0,10.5,9.3,8.0,7.1,6.2,5.4
2,11.50000,19.9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,23.0,20.6,18.3,16.3,14.3,12.5,11.0,9.6,8.6,7.6
3,7.96000,19.2,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,20.7,18.7,16.1,14.3,12.2,10.3,8.7,7.4,6.2,5.2
4,24.00000,22.1,100.0,100.0,100.0,100.0,100.0,100.0,100.0,99.9,...,15.3,12.8,11.2,9.6,8.3,6.9,5.8,5.1,4.2,3.6
5,2.07000,19.8,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,27.1,24.7,22.6,20.7,19.2,17.4,15.7,14.1,12.6,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,0.00275,10.9,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,46.7,41.6,38.4,35.7,33.0,30.3,27.6,25.2,23.1,21.0
103,0.00750,12.7,100.0,100.0,100.0,99.7,99.4,99.3,99.1,99.1,...,37.1,33.1,30.0,27.5,25.3,22.9,20.6,18.3,16.6,14.7
104,0.00208,6.4,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,98.9,97.9,96.9,95.7,77.7,55.1,45.1,36.9,29.8,29.8
105,0.00247,9.7,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,61.2,54.8,47.8,41.0,34.8,29.4,24.8,21.1,18.0,15.0
106,0.00062,5.5,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,...,76.7,67.2,60.7,54.9,48.7,42.4,37.5,33.3,29.7,26.0

# Calcs

In [89]:
import math
INTERFACIAL_TENSION = 484
CONTACT_ANGLE_DEGREES = 140

def degree_to_radian(degrees:float):
    return degrees * math.pi / 180

def J(
        capillary_pressure:float,
        wetting_phase_saturation:float,
        permeability:float,
        porosity:float,
        interfacial_tension:float = INTERFACIAL_TENSION,
        contact_angle_degrees:float = CONTACT_ANGLE_DEGREES,
):
    numerator = capillary_pressure * wetting_phase_saturation
    denominator = interfacial_tension * math.cos(degree_to_radian(CONTACT_ANGLE_DEGREES))
    if denominator == 0 or porosity == 0:
        raise ValueError("denominator or porosity cannot be zero")
    quotient = numerator / denominator
    scaling_factor = math.sqrt(permeability/porosity)
    return quotient * scaling_factor

for sample in df.index:
    try:
        df.loc[sample, 'J'] = J(
            capillary_pressure=df.loc[sample, 'pc'],
            wetting_phase_saturation=df.loc[sample, 'wp'],
            permeability=df.loc[sample, 'permeability (md)'],
            porosity=df.loc[sample, 'porosity (%)'],
        )
    except ValueError as e:
        print(f"Error in sample {sample}: {e}")

KeyError: 'pc'